### ISSUE TITLE
java.lang.ClassCastException is thrown when boxing a PrefixExpression

### ISSUE THREAD

**Issue by sh5i** [katsuhisamaruyama/jxplatform#2]
When applying CFG/PDG analysis to the following code, a ClassCastException is thrown.

```
public class C {
  void foo(Object o) {}
  void bar() {
    boolean b = true;
    foo(!b);
  } 
}
```

```
java.lang.ClassCastException: org.jtool.eclipse.model.java.JavaExpression cannot be cast to org.jtool.eclipse.model.java.JavaLocal
    at org.jtool.eclipse.model.cfg.internal.ExpressionVisitor.createActualOut(ExpressionVisitor.java:815)
    at org.jtool.eclipse.model.cfg.internal.ExpressionVisitor.createActualOuts(ExpressionVisitor.java:802)
    at org.jtool.eclipse.model.cfg.internal.ExpressionVisitor.visit(ExpressionVisitor.java:528)
    at org.eclipse.jdt.core.dom.MethodInvocation.accept0(MethodInvocation.java:231)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
...
```

https://github.com/katsuhisamaruyama/jxplatform/blob/master/org.jtool.eclipse/src/org/jtool/eclipse/model/cfg/internal/ExpressionVisitor.java#L815
ExpressionVisitor.createActualOut(...) assumes that `ain.getJavaElement()` returns JavaLocal, but this is not always true. For example, visit(PrefixExpression) assigns a JavaExpression by `curNode.setJavaElement()`, and it breaks this assumption.
https://github.com/katsuhisamaruyama/jxplatform/blob/master/org.jtool.eclipse/src/org/jtool/eclipse/model/cfg/internal/ExpressionVisitor.java#L287

This bug was found by: Fumiki Minami

**Comment by katsuhisamaruyama** [comment]
Thanks, I've fixed this bug.
Surely, ain.getJavaElement() returns JavaExpression if an argument of method invocation contains assignment.
